### ISSUE TITLE
Bit manipulations and other inlines may not work as intended

### ISSUE THREAD

**Issue by xoorath** [AlexSabourinDev/cpp-utility#8]
> include/utility/BitManipulations.h

Using the `inline` keyword may not have your code working as intended, as it's only a hint to the compiler and the compiler is under no obligation to listen to it. If you *really* know you want your code to be inlined you may want to use the strongest terms possible, which is compiler dependent. In MSVC `__forceinline` is a stronger hint, for example.

My guess is that this code will always be inlined even without the keyword based on how few instructions you will be generating in each function. You might want to see for yourself what assembly is generated when it's used in big and small functions, in loops and not. It might help you inform that decision before deciding to give hints to the compiler.

**Comment by AlexSabourinDev** [comment]
I had used the inline keyword in order to avoid errors due to the one definition rule for defining a global function in a header file. (I wanted to maintain all the functionality within the bit manipulations header.) The inlining of the method was also a thought, but not a requirement for the method as I figured the compiler would do what it wanted with the method nonetheless. 

The inlining was due mostly to things heard from other programmers and so I decided to research it more and test it out.

What I found is:

> A function marked inline (implicitly or explicitly) may be defined in several TUs (respecting the ODR), whereas it is not the case for regular functions.

Source: https://stackoverflow.com/questions/10103161/inline-keyword-vs-header-definition

Of course, my reasoning for using it was based on shaky knowledge, so I'm glad I researched it. And I definitely will check out the assembly, I think that's a good learning exercise and it will definitely help me see what the compiler is doing to my code.

I also tested the code without the inline keyword and it did cause a multiply defined symbol error when included in multiple translation units.

Other relevant sources: 
- https://stackoverflow.com/questions/1073754/linker-error-on-having-non-inline-function-defined-in-header-file
- https://stackoverflow.com/questions/39652884/one-definition-rule-multiple-definition-of-inline-functions
